### PR TITLE
Move project to maven

### PR DESCRIPTION
**Pull request by dadoonet**
This PR moves from Ant to Maven and splits the code into multiple maven modules:

* parent
* core
* client
* server
* integration tests

Some refactoring work is needed. Probably some classes only make sense within their own module. For now, almost everything is still in core module.

The final goal is to be able to release and share in maven central the project so anyone could depend on it in their own projects.

### CODE REVIEW

**Comment by usrflo** [comment]
@dadoonet +1 for these changes.
@perlundq, do you tend to accept these changes when finalized? I'd like to continue my work on a consolidated code base.

**Comment by perlundq** [comment]
I am OK with moving to maven and appreciate the effort. However I do not like unnecessary changes and I am not familiar enough with Maven conventions, so can you please explain the reasoning behind how this is divided into separate modules (I am not objecting against them I just want an argument for doing it like this)? I mean, what would happen if you would keep the layout as it was before?

And would it work out to put yajsync and yajsyncd into one single module called yajsync-cli (and I think some more belongs outside of core, see com.github.perlundq.yajsync.ui/*)?

I will learn more about Maven and then make a more detailed review shortly after christmas, but I noticed some trivial things that you can fix like:
- I would appreciate if you could avoid including the unnecessary changes of import statements.
- License should be GPL 3 or higher
- jsync -> yajsync
thanks,

**Comment by dadoonet** [comment]
Hi @perlundq. I updated the PR.

About your questions:

> can you please explain the reasoning behind how this is divided into separate modules?

Mostly because of my maven experience :) I really like the separation of concerns in Maven. You can overload a single maven project to build multiple artifacts at once but it makes the `pom.xml` file very complex and IMO maven principle is basically one module per artifact you want to build.
Also, having integration tests as a separate module actually helps you to really test the module you built previously. If you put all things all together within a single project, then the `assembly` will happen after all tests and you won't really test artifacts you are building. There might be some workarounds but I think it would make the `pom.xml` file super complicated and harder to maintain.

> And would it work out to put yajsync and yajsyncd into one single module called yajsync-cli

If you want to be able to run a JAR without specifying the classname, then I think you need 2 jars. So IMO two modules. May be you can call the shade plugin twice? But same arguments as previous ones. It would complicate the pom file.

I hope this makes sense.

**Comment by dadoonet** [comment]
Ping? Anything I can do to move this forward?

**Comment by perlundq** [comment]
Yes, do you have any idea on how to integrate eclipse with this?

**Comment by dadoonet** [comment]
IIRC the m2e plugin should work pretty well out of the box?

**Comment by usrflo** [comment]
@dadoonet : currently I see that after a split the maven project "client" would contain com.github.perlundq.yajsync.ui.YajSyncClient and "server" would contain com.github.perlundq.yajsync.ui.YajSyncServer. Nearly everything else would be in "core".
The reason for this split may be the packaging of different JARs for client and server.

Why not leaving everything in one project with packaging one JAR that contains client and server classes? This way the integration tests would be just part of the single project and no split would be necessary.

**Comment by perlundq** [comment]
@dadoonet OK, thanks, I got it to work by excluding the yajsync-parent pom when importing a new eclipse project from maven

**Comment by perlundq** [comment]
I'd like to separate the client and server code from the library part somehow. This is especially important if the library in the future will have another license than the client/server (GPL for client/server and possibly LGPL for the library/core). Is it OK to use separate licenses like that in a single Maven project?

If possible this would then be at least 2 modules.

But I also think it maybe would be cleaner to have a single module (and single jar) for both the client and the server, and let the user specify the client/server class to call (or have a single main that dispatches to the client or server depending on first arg). E.g.

java -jar yajsync-cmd/target/yajsync-0.9.0-SNAPSHOT.jar client -h
java -jar yajsync-cmd/target/yajsync-0.9.0-SNAPSHOT.jar server -h
or (maybe not as nice):
java -jar yajsync-cmd/target/yajsync-0.9.0-SNAPSHOT.jar com.github.perlundq.yajsync.server.YajSyncClient -h

and remove the yajsync-integration-tests and put that into the same module above?

**Comment by dadoonet** [comment]
> Is it OK to use separate licenses like that in a single Maven project?

I believe so although I have no experience about this.
Actually, each file in the project should have a license in its header. So you can basically mix licenses within the same project I guess.

> But I also think it maybe would be cleaner to have a single module (and single jar) for both the client and the server, and let the user specify the client/server class to call (or have a single main that dispatches to the client or server depending on first arg).

I really like this idea. I did not do the PR initially like this because I tried not to change the current behavior but definitely that's the path to explore IMO.

> remove the yajsync-integration-tests and put that into the same module above

Of course this would work technically speaking.
By experience, I think it's cleaner to have IT in another project (module) so IT module depends actually on the JAR files you generated before and not on a classpath generated by Maven.
I mean that when you do the assembly and package the final JAR, you might introduce some issues (forget to import a class or a dependency, whatever..). If you don't test the final JAR which has been generated, you can't really make sure that it's correctly built.

But, you own this project. Just tell me what you prefer and I'll update the PR accordingly.

**Comment by perlundq** [comment]
I have made a separate commit based on your pull request in 623c761696dee70f7dabb57a0bb91f4c3c11c92. I have made the following modifications though: 
    - No separate Maven module for integration tests. Such a module can easily be added later if there is a problem with the current layout.
    - Use one single Maven module for both yajsync client and server.
    - Use single jar for both yajsync client and server and add a Main class that dispatches to client and server depending on first arg.

Since it is based on this pull request I have given you credit in the commit message and also in the newly added CONTRIBUTORS file.

Thanks!

**Comment by dadoonet** [comment]
Thanks. And sorry I did not create another PR. No bandwidth for it :(

**Pull request closed without merging**
