### PR TITLE
Add --ignore-times

### PR DESCRIPTION
**Pull request by usrflo**
This pull request is related to issue https://github.com/perlundq/yajsync/issues/26

### CODE REVIEW

**Comment by perlundq** [comment]
Looks good. Please remove the trailing white spaces in there and squash the separate commits into one (and while you're at it you might as well change the commit message to present tense "Add support for --ignore-times") and I'll merge it. Thanks.

**Comment by usrflo** [comment]
> Please remove the trailing white spaces in there

I can't detect any trailing white space on the 62 changed lines. Can you please give an example (<filename>:<line number>) ?

**Comment by perlundq** [comment]
Use git diff --check (please read CONTRIBUTING.md - this will work if you have the yajsync git repo configured with core.whitespace trailing-space,space-before-tab,tab-in-indent,tabwidth=4)
```
$ git diff HEAD~2 --check
src/main/com/github/perlundq/yajsync/session/Generator.java:162: trailing whitespace.
+
src/main/com/github/perlundq/yajsync/session/RsyncClientSession.java:69: trailing whitespace.
+
src/main/com/github/perlundq/yajsync/session/RsyncClientSession.java:143: space before tab in indent.
+               sb.append("I");
src/main/com/github/perlundq/yajsync/session/RsyncLocal.java:81: trailing whitespace.
+
src/main/com/github/perlundq/yajsync/session/RsyncLocal.java:84: space before tab in indent.
+       _isIgnoreTimes = isIgnoreTimes;
src/main/com/github/perlundq/yajsync/session/ServerSessionConfig.java:287: trailing whitespace.
+                    }}));
src/main/com/github/perlundq/yajsync/session/ServerSessionConfig.java:288: trailing whitespace.
+
src/main/com/github/perlundq/yajsync/session/ServerSessionConfig.java:459: trailing whitespace.
+
src/main/com/github/perlundq/yajsync/session/ServerSessionConfig.java:462: space before tab in indent.
+       _isIgnoreTimes = true;
src/main/com/github/perlundq/yajsync/session/ServerSessionConfig.java:494: trailing whitespace.
+
src/main/com/github/perlundq/yajsync/ui/YajSyncClient.java:395: trailing whitespace.
+
src/main/com/github/perlundq/yajsync/ui/YajSyncClient.java:404: space before tab in indent.
+                       _isIgnoreTimes  = true;
```

**Comment by usrflo** [comment]
I struggled a bit with git, auto-merge should work now. Please recheck.

**Pull request merged**
